/**
 * Every IPC channel the renderer may call. The preload script only forwards channels listed here, and the
 * main process re-validates each call (authentication, permissions and Zod schemas).
 * tests/channels.test.ts keeps this list in sync with src/core/api.ts.
 */
export const CORE_CHANNELS = [
  'auth:status',
  'auth:setup',
  'auth:login',
  'auth:logout',
  'auth:recover',
  'auth:changePassword',
  'settings:get',
  'settings:update',
  'settings:confirmAddress',
  'categories:list',
  'categories:save',
  'products:list',
  'products:get',
  'products:byCode',
  'products:create',
  'products:update',
  'products:setActive',
  'catalogue:status',
  'catalogue:markReviewed',
  'catalogue:flag',
  'catalogue:approve',
  'catalogue:reset',
  'catalogue:export',
  'catalogue:importPreview',
  'catalogue:importCommit',
  'inventory:movements',
  'inventory:adjust',
  'inventory:setOpening',
  'inventory:previewStockCsv',
  'inventory:valuation',
  'inventory:reconcile',
  'inventory:count',
  'inventory:lowStock',
  'suppliers:list',
  'suppliers:save',
  'purchases:list',
  'purchases:get',
  'purchases:create',
  'billing:create',
  'invoice:html',
  'sales:list',
  'sales:get',
  'sales:findByNo',
  'sales:cancel',
  'sales:collectDue',
  'returns:create',
  'returns:list',
  'customers:list',
  'customers:save',
  'dashboard:get',
  'reports:run',
  'reports:export',
  'expenses:list',
  'expenses:create',
  'expenses:void',
  'users:list',
  'roles:list',
  'users:create',
  'users:update',
  'roles:setPermissions',
  'audit:list',
  'backup:list',
  'backup:createTo',
  'backup:inspect',
  'backup:integrity',
  'backup:restore',
  'util:csvTemplate',
] as const;

/** Channels implemented in the Electron main process (native dialogs, printing, app info). */
export const NATIVE_CHANNELS = [
  'dialog:saveFile',
  'dialog:openText',
  'dialog:chooseFolder',
  'dialog:chooseBackupFile',
  'print:invoice',
  'print:test',
  'app:info',
  'app:showDataFolder',
] as const;

export const ALL_CHANNELS: readonly string[] = [...CORE_CHANNELS, ...NATIVE_CHANNELS];
export type Channel = (typeof CORE_CHANNELS)[number] | (typeof NATIVE_CHANNELS)[number];

export const IPC_INVOKE = 'skb:invoke';
